### ISSUE TITLE
Question: Websockets and MasterProxy

### ISSUE THREAD

**Issue by alanpeabody** [wojtekmach/acme_bank#1]
Hi @wojtekmach,

Thanks again for this awesome example and talk, I am studying this and had some questions. I hope you don't mind if I open issues here.

My question is around websockets. I have a similar situation where there is both a "public" and an "admin" client that would be great fit for two different phoenix apps in an umbrella. However at least one of them needs a websocket connection as well as an API.

I believe in this example app websockets would not be supported because plug doesn't support them. Have you thought about this at all?

I am assuming you would have to use Phoenix.Endpoint in the masterproxy app (but maybe not as a Phoenix app?). Anything to consider with that?

**Comment by wojtekmach** [comment]
Hey @alanpeabody sorry for a late reply. I haven't yet explored websockets in this setup, so unfortunately I can't help you out at this moment.

Please keep in mind that MasterProxy is really only needed because I happen to deploy to Heroku, and I needed to expose a single web port; perhaps in your particular case it would be easier to deploy your umbrella with releases and either deploy separate web apps to separate nodes (thus not needing proxy) and/or set up e.g. nginx in front - check out distillery for a great out-of-the-box support for deploying umbrella projects. Alternatively, MasterProxy could be extended to start separate Cowboy websocket handler and route the requests to phoenix apps, although I haven't tried that. Finally, I think MasterProxy could be rewritten as a Phoenix app in which case it would handle the websockets, and you'd route the calls to channels yourself but I haven't tried that either.

I'm closing this thread as it's not actionable to this repo, but feel free to keep discussing it. Sorry I couldn't be of more help!
