### ISSUE TITLE
Error when trying to run two instances of the app from MasterProxy

### ISSUE THREAD

**Issue by enilsen16** [wojtekmach/acme_bank#10]
```elixir
[error] Failed to start Ranch listener MasterProxy.Plug.HTTP in :ranch_tcp:listen([port: 3333]) for reason :eaddrinuse (address already in use)
```

When I run `mix run --no-halt` and `iex -S mix` inside of `/apps/master_proxy`, I get the error above. I thought about trying to have something like this:

```elixir
if :erlang.whereis(MasterProxy.Plug.HTTP) == :undefined, do: [Plug.Adapters.Cowboy.child_spec(:http, MasterProxy.Plug, [], [port: port])], else: []
```

Doesn't seem to work though. Any thoughts?

**Comment by wojtekmach** [comment]
I guess this is similar when trying to run in two terminals `mix phoenix.server` and `iex -S mix phoenix.server` for any phoenix app. I'm not sure about the code change above, I think a cleaner approach would be to have a dedicated mix task that starts http. (e.g.: `cd apps/master_proxy && mix start`.)

TBH, I don't think it's a big deal and I'd just leave it as is. I almost never use master_proxy in development (because I lose live-reloading) and instead I just start in umbrella root: `iex -S mix phoenix.server`. I only really needed master_proxy for heroku deployment. If you feel like fixing it though, I'd be happy to accept a PR!

**Comment by enilsen16** [comment]
Yeah not a bad idea. When I tried to access acme_bank on heroku this is where I first had the issue actually.

**Comment by wojtekmach** [comment]
Weird, just before commenting I specifically tested if stuff was ok on
heroku and it seemed fine. the app was running and I could connect with:
heroku run iex -S mix without problems

W dniu pt., 11.11.2016 o 18:49 Erik Nilsen notifications@github.com
napisał(a):

**Comment by enilsen16** [comment]
I am not quite sure what a mix task would look like for this particular case though. What I expected was to be able to run both side by side just like `mix phoenix.server` and `iex -S mix`. After quickly glancing at what phoenix does for the `mix phoenix.server` mix task, it seems to just run `mix run --no-halt`.  

Which doesn't solve the problem of `MasterProxy.Plug.HTTP` starting twice. Maybe I am missing something but isn't that the problem?

**Comment by enilsen16** [comment]
Also I retried acme-bank on heroku. You're right it seems to work there fine, however locally I still have issues....

**Comment by enilsen16** [comment]
Closing this for now...
