### ISSUE TITLE
Question: State of balances

### ISSUE THREAD

**Issue by cdesch** [wojtekmach/acme_bank#11]
I'm new to OTP and Elixir. 

If I'm understanding this correctly, the balance for each account is kept in memory in OTP. Each time the application launches or a supervisor needs to restart a GenServer, the balance would need to be recalculated from the ledger entries in `bank_entries` table in the database. When a transaction occurs, the OTP records it to the database and transforms the values in memory. 

If a balance is queried through the web interface, it would go to the OTP bank and read it directly from memory instead of having to recalculate it. 

Is this correct? Am I understanding this the way it should be?

This call from `bank.ex`
      
      def balance(%Customer{wallet: wallet}), do: Ledger.balance(wallet)

Is calling `ledger.ex`

 ```
 def balance(%Account{id: id, type: type, currency: currency}) do
    q = from(t in Entry,
             select: fragment("SUM(CASE WHEN b0.type = 'credit' THEN (b0.amount).cents ELSE -(b0.amount).cents END)"),
             where: t.account_id == ^id)

    balance = Repo.one(q) || 0
    balance = do_balance(balance, type)
    %Money{cents: balance, currency: currency}
  end
```

and this is where it is kept in memory.

**Comment by wojtekmach** [comment]
Hi!

> If I'm understanding this correctly, the balance for each account is kept in memory in OTP. Each time the application launches or a supervisor needs to restart a GenServer, the balance would need to be recalculated from the ledger entries in bank_entries table in the database. When a transaction occurs, the OTP records it to the database and transforms the values in memory.

This is not how it is implemented here. You can look at the supervision tree and notice no such things are happening [1]. Whenever we need account's balance we go to the database and recalculate it. Turns out, it's not a big deal for the database to calculate that number even for hundreds of thousands of entries [2]. What you're suggesting would be a valid way to design it though [3] but it's not a direction I have explored yet. It's probably how Erlangers would approach the problem; I was still very much in the mindset of "sticking everything into the database".

I'm closing this issue as it's not actionable, but feel free to continue discussing this topic. Thanks for bringing this up!

[1] https://github.com/wojtekmach/acme_bank/blob/master/apps/bank/lib/bank/application.ex#L13

[2] if the sheer number of entries becomes very large, a popular solution is to "roll up" all entries before certain date into one entry, so that there's less rows to access each time. The full account history is still available, but perhaps not directly accessible (e.g. older entries are stored in a different table)

[3] (1 GenServer for account, under a supervisor with a `:simple_one_for_one` restart strategy, which allows dynamic number of child process)

**Comment by cdesch** [comment]
Thank you! This was extremely helpful! I really appreciate you taking the time to write back and I really did enjoy your [presentation](https://www.youtube.com/watch?v=6NTmUQClHrU). 

For [2] do you know of any reference code of how this might be implemented? I may try to fork your repo and attempt it, just to have experience with the two working concepts.
